Develop
Nick13Zen/Nikita-Zenchik pull request #1
Opened 2016-10-03 09:44 UTC by Nick13Zen

First three homeworks.

2016-10-03 11:26 UTC, AlexanderSoroka requested changes

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_1/src/Main.java
> +	 * Main class which contained entry point.
Indentation is wrong

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_1/src/Main.java
> +	/**
Indentation is wrong

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_1/src/Main.java
> +    }
Indentation is wrong

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_1/src/Main.java
> +
remove these useless blank lines

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_2/src/Main.java
> +        if(args.length>0)
missed {}  after if and else

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/Calculate.java
> +     /**
Indentation is wrong

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +     /**
Indentation is wrong

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +	/**
Indentation is wrong

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +
useless blank line

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +     * The method check if number is zero.
Indentation is wrong

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +			System.out.println(Helper.DIVISION_BY_ZERO);
Indentation is wrong

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +		else return false;
Missed {} in else block

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +		else return false;
Missed {} in else block

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +	/**
Indentation is wrong

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +
useless blank line

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +	else return false;
missed {} in else block

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/Helper.java
> +	public static final String ABOUT = "The program perform " +
Indentation is wrong

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/Main.java
> +                  String stringArg1 = args[0];
Indentation is wrong

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/Main.java
> +                  }
} else {

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/Main.java
> +                      if(Double.isInfinite(arg1) &&
Is it case when first is infinite and second is just number acceptable?

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/Main.java
> +                        }
Indentation is wrong

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/Main.java
> +        	System.exit(0);
missed {}

2016-10-03 11:26 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +		if(zero == 0) {
Invalid double comparison

2016-10-03 12:20 UTC, AlexanderSoroka requested changes

2016-10-03 12:20 UTC, AlexanderSoroka commented on HomeWork_2/src/Main.java
> +        }
here and everywhere must be } else [

2016-10-03 12:20 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +         if(zero == 0) {
Invalid double comparison

2016-10-03 12:54 UTC, AlexanderSoroka requested changes

2016-10-03 12:54 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +         if(!(Double.isInfinite(zero))) {
This check looks error-prone - zero is always finite I could not imagine what are you doing here

2016-10-03 13:05 UTC, Nick13Zen commented on HomeWork_3/src/CheckResult.java
> +         if(!(Double.isInfinite(zero))) {
Saw that after push. Fixed now

2016-10-03 13:21 UTC, AlexanderSoroka requested changes

2016-10-03 13:21 UTC, AlexanderSoroka commented on HomeWork_3/src/CheckResult.java
> +               return Helper.BOUNDS_ERROR;
Indentation is wrong - check it everywhere

2016-10-03 15:25 UTC, AlexanderSoroka approved these changes

2016-10-04 10:27 UTC, AlexanderSoroka requested changes

2016-10-04 10:27 UTC, AlexanderSoroka commented on HomeWork_4/src/Helper.java
> +
Useless blank line

2016-10-04 10:27 UTC, AlexanderSoroka commented on HomeWork_4/src/Helper.java
> +public class Helper {
Inappropriate class name - Helper implies that it does some work and helps, but it contains only consts. something like Messages would be more clear.

2016-10-04 10:27 UTC, AlexanderSoroka commented on HomeWork_4/src/Helper.java
> +    public static final String EMPTY = "Error. Line you entered is empty \"-help\".";
Missed blank line

2016-10-04 11:43 UTC, AlexanderSoroka requested changes

2016-10-04 11:43 UTC, AlexanderSoroka commented on HomeWork_3/src/Main.java
> +            } else {
You don't need this else

2016-10-04 11:43 UTC, AlexanderSoroka commented on HomeWork_3/src/Main.java
> +               } else {
Don't need this else

2016-10-04 11:43 UTC, AlexanderSoroka commented on HomeWork_3/src/Main.java
> +                  } else {
Don't need this else

2016-10-04 11:46 UTC, Nick13Zen commented on HomeWork_3/src/Main.java
> +            } else {
Home Work_3? I'm working on 4 and 5.

2016-10-04 14:46 UTC, AlexanderSoroka commented
It contains a lot of useless files. I'll close it, you should merge all useless files to master and leave only 4-5 source code in dev, after create new pull-request - it must contain only java code for 4 and 5

2016-10-04 14:46 UTC, closed without merging